### ISSUE TITLE
Restapi update url issue

### ISSUE THREAD

**Issue by chrisastley** [bigbridge-nl/product-import#28] opened 2021-01-26 23:33 UTC
Hi,

I've just come across an issue doing a scan of my site using screamingfrog.

Basically, when I create products I manually set the url_key attribute and the product creates/works as expected. If I revise the product with a new url_key the attribute in the database is updated but the attribute url_path retains the old value.

This is causing some strange behaviour where the canonical URL is correct and the page loads on the correct URL, but the href in the page for the scroll to review, along with the 3rd party HTML sitemap and richsnippets are showing the old URL.

I can see there is mention of the url_path attribute in the CategoryImporter.php file but nothing in any file relating to Product import, is this an oversight? Do you have a solution?

I've used this extension for generating URL keys in the past when I used magmi (https://github.com/olegkoval/magento2-regenerate_url_rewrites) and there approach appears to be set it to null before saving the product (https://github.com/olegkoval/magento2-regenerate_url_rewrites/blob/148378eb7cbd98807d1c86e6a1262763bbf77944/Model/RegenerateProductRewrites.php#L180)
Not sure if that is of any use.

Thanks in advance.

**Comment by patrick-bigbridge** [comment] 2021-01-27 08:30
I have come to understand that the url_path attribute is an old remnant that is not actively used by Magento. However, it still occurs in a check to determine if the url_key has changed (I don't understand why).

The product importer does not create the url_path attribute, and if you only use the product importer to create products, you probably would not see this issue. But I understand that you create the products manually and later update them with the importer. This is a good use case of course. And I suppose it's a good idea to have the importer _remove_ the url_path attribute in all cases. 

(It is my conviction that no null-values should be written to eav-tables. Removing the value has the same effect.)

I will look into this some more in a few days.

**Comment by chrisastley** [comment] 2021-01-27 11:01
Hi,

Thanks for the prompt reply. Just been doing some digging and I can see that the url_path is now documented as deprecated. 

The product I'm working on was created by your module only last week so I'm not sure why it would have an entry in the database for the url_path though, I have manually deleted the entry for just this single product, reindexed and cleared cache but still have the old URL showing in a couple of places which is strange as the only place the old URL exists in the database is the url_rewrite table pointing to the new URL.

Strangely I noticed in the url_rewrite table that the 301 redirect for the change of url_key had a lower id than the actual system-generated url_rewrite entries for the same product. I removed the 301 and now the link showing in the HTML sitemap and where it was wrong on the product page has corrected itself.

Do you think it's possible that a query getting the first entry for the product from that table and it is finding the old URL key in the rewrite first?

**Comment by chrisastley** [comment] 2021-01-27 11:17
I've just confirmed my thoughts. I've just done a test with an existing problem product.

The value in the database for url_path is deprecated as mentioned above. 

When I viewed the url_rewrite table for entries for a product with the issue I changed the 301 entries to have a higher id by updating them with the next available auto-increment values and then reindexed, cleared cache and the problem was resolved for that product.

I'm not sure how the 301 has a lower id than the system generated ones though.

**Comment by chrisastley** [comment] 2021-01-27 11:28
To test this further I have just written the following SQL query to find products with the 301 id less than the system id and the output matches my issues flagged by the screamingfrog site crawl.

`SELECT rew.*, sys.url_rewrite_id FROM url_rewrite AS rew
LEFT JOIN url_rewrite AS sys ON rew.entity_type = sys.entity_type AND rew.entity_id = sys.entity_id AND rew.store_id = sys.store_id
WHERE rew.redirect_type = '301'
AND rew.url_rewrite_id < sys.url_rewrite_id
AND sys.target_path NOT LIKE '%/category/%'
AND rew.store_id = 1`

**Comment by chrisastley** [comment] 2021-01-27 13:48
Update.

I've created this script to put on a cron that has resolved the issue for now, but ideally it needs sorting at source and not having to alter the table to fix the issue.

`use Magento\ Framework\ App\ Bootstrap;
require __DIR__ . '/../app/bootstrap.php';
$params = $_SERVER;
$bootstrap = Bootstrap::create( BP, $params );
$objectManager = $bootstrap->getObjectManager();
$state = $objectManager->get( Magento\ Framework\ App\ State::class );
$state->setAreaCode( 'adminhtml' );
$objectManager->get('Magento\Framework\Registry')->register('isSecureArea', true);

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableUR = $resource->getTableName('url_rewrite');

$sql = "SELECT rew.*, sys.url_rewrite_id AS old_id FROM `" . $tableUR . "` AS rew
    LEFT JOIN `" . $tableUR . "` AS sys ON rew.entity_type = sys.entity_type AND rew.entity_id = sys.entity_id AND rew.store_id = sys.store_id AND rew.target_path = sys.request_path
    WHERE rew.redirect_type = '301'
    AND rew.url_rewrite_id < sys.url_rewrite_id
    AND sys.target_path NOT LIKE '%/category/%';
";
echo "<hr/><xmp>".print_r($sql, true)."</xmp>";
$issues = $connection->fetchAll($sql);

foreach ($issues as $issue) {
    echo "<hr/><xmp>".print_r($issue, true)."</xmp>"; //die;

    // Replace 301 entry to increase auto_increment to be greater than system generated entry
    $sql = "REPLACE INTO `" . $tableUR . "`(`entity_type`, `entity_id`, `request_path`, `target_path`, `redirect_type`, `store_id`, `description`, `is_autogenerated`, `metadata`) 
        VALUES
        ('".$issue['entity_type']."','".$issue['entity_id']."','".$issue['request_path']."','".$issue['target_path']."','".$issue['redirect_type']."','".$issue['store_id']."','".$issue['description']."','".$issue['is_autogenerated']."','".$issue['metadata']."');";
    echo "<hr/><xmp>".print_r($sql, true)."</xmp>";
    $connection->query($sql);
}`

**Comment by patrick-bigbridge** [comment] 2021-01-27 13:58
Hi Chris,

Sorry I don't have much time right now. But I recognize the problem because a colleague of me ran into it a week ago. I then figured it was a Magento problem since it took a 301 to be the current rewrite, which is obviously wrong. 

Apparently Magento makes use of the fact that the 301 is placed after the non-redirects in the database. An assumption that is true when products are manipulated via the backend user interface. Apparently my importer happens to write the 301 first when it updates the product. It shouldn't have mattered. But obviously it does, and I will make the change in a few days.

**Comment by chrisastley** [comment] 2021-01-27 14:02
No problem, thanks for the update. Wasn't pushing you but just updating you on my findings and that I have a temporary workaround running on a cron.

Not sure how to paste code in here with back ticks and line breaks so apologies;

use Magento\ Framework\ App\ Bootstrap;
require __DIR__ . '/../app/bootstrap.php';
$params = $_SERVER;
$bootstrap = Bootstrap::create( BP, $params );
$objectManager = $bootstrap->getObjectManager();
$state = $objectManager->get( Magento\ Framework\ App\ State::class );
$state->setAreaCode( 'adminhtml' );
$objectManager->get('Magento\Framework\Registry')->register('isSecureArea', true);

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableUR = $resource->getTableName('url_rewrite');

$sql = "SELECT rew.*, sys.url_rewrite_id AS old_id FROM `" . $tableUR . "` AS rew
    LEFT JOIN `" . $tableUR . "` AS sys ON rew.entity_type = sys.entity_type AND rew.entity_id = sys.entity_id AND rew.store_id = sys.store_id AND rew.target_path = sys.request_path
    WHERE rew.redirect_type = '301'
    AND rew.url_rewrite_id < sys.url_rewrite_id
    AND sys.target_path NOT LIKE '%/category/%';
";
echo "<hr/><xmp>".print_r($sql, true)."</xmp>";
$issues = $connection->fetchAll($sql);

foreach ($issues as $issue) {
    echo "<hr/><xmp>".print_r($issue, true)."</xmp>"; //die;

    // Replace 301 entry to increase auto_increment to be greater than system generated entry
    $sql = "REPLACE INTO `" . $tableUR . "`(`entity_type`, `entity_id`, `request_path`, `target_path`, `redirect_type`, `store_id`, `description`, `is_autogenerated`, `metadata`) 
        VALUES
        ('".$issue['entity_type']."','".$issue['entity_id']."','".$issue['request_path']."','".$issue['target_path']."','".$issue['redirect_type']."','".$issue['store_id']."','".$issue['description']."','".$issue['is_autogenerated']."','".$issue['metadata']."');";
    echo "<hr/><xmp>".print_r($sql, true)."</xmp>";
    $connection->query($sql);
}

**Comment by patrick-bigbridge** [comment] 2021-02-01 15:00
Hello Chris,

preliminary report:

A) I will add code that removes `url_path` from imported products.

B) In my opinion Magento has a bug in 

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Url.php

The array $filterData should have a constraint on the redirect type, like this

`$filterData['redirect_type'] = 0`

I am not going to file this "bug", because Magento may rightly claim that this is by design, and when properly used, a redirect must always succeed the original.

Instead, I am going to write the 301's at the end. Currently working on this.

**Comment by chrisastley** [comment] 2021-02-01 15:03
Hi Patrick,

Thanks for the update and for looking at removing the url_path when doing a revise.

**Comment by patrick-bigbridge** [comment] 2021-02-05 15:02
Hello Chris,

Ah, url rewrites, the joy they bring. ;)

I have updated the url_rewrite generation code. It now makes sure that non-redirects are placed before redirects. This has become release 1.5.4

By itself, this will only take care that new url_rewrites are created in the right order. It will not repair existing rewrites.

If you need to fix all existing url_rewrites, here is a recipe for that:

First, delete all non-redirects; this will cause the urlrewrite-tool to discover something's missing. 

Note: This will corrupt the url_rewrite table and make the website unusable, so do this at a quite time. You may also consider dumping the url_rewrite table just to be safe: `mysqldump some_database url_rewrite > url_rewrite.sql`

`delete from url_rewrite where entity_type = 'product' and redirect_type = 0;`

Then run the urlrewrite tool

`bin/magento bigbridge:product:urlrewrite` (with the necessary options)

This will repair the url_rewrites by removing them and re-adding them, with the new non-redirect up front.

**Comment by chrisastley** [comment] 2021-02-05 15:42
Hello Patrick, 

Thanks for the update that addresses the issue.

**Comment by chrisastley** [comment] 2021-02-05 15:47
One more question relating to product rewrites. 

I'm currently having to use this command regularly

bin/magento bigbridge:product:urlrewrite --category-path-urls delete

Is it possible for the import/update procedure to not create them in the first place based on the config value stored in the core_config_data table for `catalog/seo/generate_category_product_rewrites`

**Comment by patrick-bigbridge** [comment] 2021-02-05 16:01
No, I created this code before Magento added that option. But I will put it on my list.

Currently you can prevent the creation of these path-urls by adding the option `category-path-urls=delete` to the import.

**Comment by chrisastley** [comment] 2021-02-05 16:12
That's good to know, thank you.

**Comment by patrick-bigbridge** [comment] 2021-02-08 08:10
I'll close this issue for now. You can reopen it if anything new comes up.

**Closed by patrick-bigbridge** 2021-02-08 08:10 UTC
